backend:
  name: github # git-gateway
  repo: ekoindia/empages # Path to your Github repository
  branch: master # Branch to update (optional; defaults to master)
media_folder: images
public_folder: /images
collections:
  - name: help
    label: Agent Help Docs
    folder: _help/
    media_folder: /images/help
    public_folder: /empages/images/help
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'help' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: admin_sop
    label: Admin SOPs
    folder: _admin_sop/
    media_folder: /images/_admin_sop
    public_folder: /images/_admin_sop
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'help' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
